### Create a new report
POST http://localhost:3000/reports
content-type: application/json

{
 "make": "Ford",
 "model": "mustang",
 "year": 1988,
 "mileage": 15000,
 "lng": 45,
 "lat": 45,
 "price": 20000 
}

### Update Approval request

PATCH http://localhost:3000/reports/10
Content-Type: application/json

{
    "approved": true
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=ford&model=mustang&lng=45&lat=45&mileage=10000&year=1985
